# Generated by Django 5.1.6 on 2025-02-19 21:25

import apps.accounts.models.user
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.address",
                verbose_name="endereço",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Feminino")],
                max_length=1,
                null=True,
                verbose_name="gênero",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.accounts.models.user.upload_to,
                verbose_name="foto de perfil",
            ),
        ),
    ]
