# Generated by Django 5.1.6 on 2025-02-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="active",
            field=models.BooleanField(default=True, verbose_name="ativo"),
        ),
        migrations.AlterField(
            model_name="order",
            name="cart",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="purchase.cart",
                verbose_name="carrinho",
            ),
        ),
    ]
